# Generated by Django 2.2.5 on 2019-09-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ide', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField(max_length=200)),
                ('respuestas', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('ide', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('contenido', models.TextField(max_length=200)),
                ('Post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.Post')),
            ],
        ),
    ]
